baseurl = "https://escritos-matiasandina.netlify.com/"
title = "Escritos"
author = "Matias Andina"
canonifyurls = true
languagecode = "es"
theme = "black-and-light"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "UNPUBLISHED"]
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
googleAnalytics = "UA-164651073-1"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Matias Andina"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://matiasandina.netlify.com/about/"
    weight = 1
[[menu.main]]
    name = "Contribuir"
    url  = "/contribute"
    weight = 2
[[menu.main]]
	name       = "Contacto"
	url        = "/contact"
	weight     = 3

[taxonomies]
  tag      = "tags"